### ISSUE TITLE
Cyclic-reboot.

### ISSUE THREAD

**Issue by SmallSharkUA** [InverseRE/antiflood#2]
Check that device reboot once a month. Fix CPU time calculation after deep sleep.

**Comment by InverseRE** [comment]
Cyclic reboot to prevent timer overflow.
May be used as a part of valve's routine cleaning.

**Comment by InverseRE** [comment]
http://donalmorrissey.blogspot.com/2010/04/putting-arduino-diecimila-to-sleep-part.html
